### ISSUE TITLE
期望提供一个1.3版本的

### ISSUE THREAD

**Issue by litianwang** [zhangmy163/dolphinScheduler#1]
期望提供一个1.3版本的

**Comment by zhangmy163** [comment]
好的，这几天我抽时间弄一下看看。

**Comment by zhangmy163** [comment]
> 期望提供一个1.3版本的

好的这几天我抽时间弄一下试试。如果变化不大应该好弄。

**Comment by zhangmy163** [comment]
已经提交。

`docker pull minimy/dolphinscheduler:1.3.1`

**Comment by zhangmy163** [comment]
已经提交

`docker pull minimy/dolphinscheduler:1.3.1`
